export default {
  menu: {
    motorCtrl: 'Control',
    spdMonitor: 'Monitor',
    startupTest: 'StartStop',
    setting: 'Settings',
  },
  main: {
    title: 'Motor Control',

    motorCfg: 'Motor Config',
    serialPort: 'SerialPort',
    baudRate: 'BaudRate',
    ctrlMode: 'Ctrl Mode',
    identify: 'Motor Identify',
    rsOnline: 'Rs Online',
    rsReCalc: 'Rs Recalc',
    targetRps: 'Target Rps',
    targetPos: 'Target Pos',
    connect: 'Connect',
    disconnect: 'Disconnect',
    start: 'Start',
    update: 'Update',
    stop: 'Stop',
    speedMode: 'speedMode',
    posMode: 'positionMode',
    lineCurve: 'lineCurve',

    realTimeSpd: 'RealTime Speed',
    realTimePos: 'RealTime Position',

    status: 'Status and Params',
    identifiedStatus: 'Motor Identified Status',
    motorStatus: 'Motor Status',
    mcStatus: 'MC Status',
    errorCode: 'Error Code',
    clearFaults: 'Ack Fault',
    magPoles: 'Mag Poles',
    busVol: 'VBus Voltage',
    maxAcc: 'Max Accelerate',
    startAcc: 'Startup Accelerate',
    fwVersion: 'Firmware Version',
    upgrade: 'Upgrade',
  },
  spdMonitor: {
    title: 'Speed Monitor',
    trend: 'Speed Trend',
    trendSetting: 'Settings',
    ovservePoints: 'Points',
    startObserve: 'Observe',
    spdRecord: 'Speed Record',
    recordLocation: 'Location',
    recordDuration: 'Duration',
    startRecord: 'Record',
  },
  startStop: {
    title: 'StartUp Test',
    logs: 'Logs',
    timeStamp: 'TimeStamp',
    message: 'Message',

    settings: 'Setting',
    testCnt: 'Test Count',
    targetRps: 'Target Rps',
    rotateDuration: 'Rotate Duration',
    coldDuration: 'Cold Duration',

    relay: 'Relay',
    relayPort: 'Port',
    relayBaud: 'Baudrate',
    relayConnect: 'Connect',
    relayDisconnect: 'Disconnect',
    relayStart: 'Start',
    relayStop: 'Stop',

    status: 'Status',
    SuccessCnt: 'Success Cnt',
    FailedCnt: 'Failed Cnt',
    testDuration: 'Duration',
  },
  settings: {
    title: 'Settings',
    motorSetting: 'Motor',
    motorSpecialParamsSetting: 'Special Params Setting',
    encoderSetting: 'encoder Setting',

    tools: 'Tools',
    mergeHex: 'Merge Hex',

    systemSetting: 'System',
    language: 'Language',
    darkMode: 'Dark Mode',
    checkUpdate: 'Ckeck Updates',
    appVersion: 'App Version',

    alreadyUpdated: 'It is the latest version now',
  },

  stop: 'Stop',
  start: 'Start',
  update: 'Update',
  fwUpgrade: 'Upgrade Fw',
  download: 'Download',
  downloading: 'Downloading',
  selectFile: 'Select File',
}